In [1]:
#1
import numpy as np

arr = np.arange(6)
print(arr.dtype)


int64


In [2]:
#2
arr = np.array([1.5, 2.6, 3.7])
if arr.dtype == np.float64:
    print("The data type is float64")
else:
    print("The data type is not float64")


The data type is float64


In [3]:
#3
arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)
print(arr)


[1.+2.j 3.+4.j 5.+6.j]


In [4]:
#4
arr = np.array([1, 2, 3, 4, 5])
arr_float32 = arr.astype(np.float32)
print(arr_float32)


[1. 2. 3. 4. 5.]


In [5]:
#5
arr = np.array([1.234567890123456, 2.345678901234567, 3.456789012345678], dtype=np.float64)
arr_float32 = arr.astype(np.float32)
print(arr_float32)


[1.2345679 2.3456788 3.456789 ]


In [6]:
#6
def array_attributes(arr):
    return arr.shape, arr.size, arr.dtype

arr = np.array([1, 2, 3, 4, 5])
print(array_attributes(arr))


((5,), 5, dtype('int64'))


In [7]:
#7
def array_dimension(arr):
    return arr.ndim

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(array_dimension(arr))


2


In [8]:
#8
import numpy as np

def item_size_info(arr):
    item_size = arr.itemsize  # Size of one element in bytes
    total_size = arr.nbytes  # Total size in bytes
    return item_size, total_size

# Example usage
arr = np.array([1, 2, 3, 4, 5], dtype=np.int32)
print(item_size_info(arr))


(4, 20)


In [9]:
#9
import numpy as np

def array_strides(arr):
    return arr.strides

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
print(array_strides(arr))


(12, 4)


In [10]:
#10
import numpy as np

def shape_stride_relationship(arr):
    return arr.shape, arr.strides

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(shape_stride_relationship(arr))


((2, 3), (24, 8))


In [11]:
#11
import numpy as np

def create_zeros_array(n):
    return np.zeros(n)

# Example usage
print(create_zeros_array(5))


[0. 0. 0. 0. 0.]


In [12]:
#12
import numpy as np

def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

# Example usage
print(create_ones_matrix(3, 4))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
#13
import numpy as np

def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

# Example usage
print(generate_range_array(0, 10, 2))


[0 2 4 6 8]


In [14]:
#14
import numpy as np

def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

# Example usage
print(generate_linear_space(0.0, 1.0, 5))


[0.   0.25 0.5  0.75 1.  ]


In [15]:
#15
import numpy as np

def create_identity_matrix(n):
    return np.eye(n)

# Example usage
print(create_identity_matrix(3))


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
#16
import numpy as np

def list_to_numpy_array(py_list):
    return np.array(py_list)

# Example usage
my_list = [1, 2, 3, 4, 5]
print(list_to_numpy_array(my_list))


[1 2 3 4 5]


In [17]:
#17
import numpy as np

# Creating the original NumPy array
arr = np.array([1.5, 2.6, 3.7])

# Creating a view of the original array
arr_view = arr.view()

# Modifying the view will reflect in the original array
arr_view[0] = 9.8

print("Original Array:", arr)
print("View Array:", arr_view)


Original Array: [9.8 2.6 3.7]
View Array: [9.8 2.6 3.7]


In [18]:
#18
import numpy as np

def concatenate_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)

# Example usage
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(concatenate_arrays(arr1, arr2, axis=0))
print(concatenate_arrays(arr1, arr2, axis=1))


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [19]:
#19
import numpy as np

# Creating two arrays with different shapes
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[4, 5, 6], [7, 8, 9]])

# Concatenating horizontally (along axis 1)
concatenated = np.concatenate((arr1, arr2), axis=0)

print(concatenated)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
#20
import numpy as np

def vertical_stack(arr_list):
    return np.vstack(arr_list)

# Example usage
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])
print(vertical_stack([arr1, arr2, arr3]))


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
#21
import numpy as np

def generate_range_array(start, stop, step):
    return np.arange(start, stop+1, step)

# Example usage
print(generate_range_array(1, 10, 2))


[1 3 5 7 9]


In [22]:
#22
import numpy as np

def generate_equal_space():
    return np.linspace(0, 1, 10)

# Example usage
print(generate_equal_space())


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [23]:
#23
import numpy as np

def generate_log_space():
    return np.logspace(0, 3, 5)

# Example usage
print(generate_log_space())


[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [24]:
#24
import numpy as np
import pandas as pd

def create_dataframe():
    data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    df = pd.DataFrame(data, columns=['A', 'B', 'C'])
    return df

# Example usage
print(create_dataframe())


   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


In [25]:
#25
import pandas as pd
import numpy as np

def replace_negatives_with_zeros(df, column_name):
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df

# Example usage
data = {'A': [1, -2, 3, -4, 5], 'B': [5, -6, 7, -8, 9]}
df = pd.DataFrame(data)
print(replace_negatives_with_zeros(df, 'A'))


   A  B
0  1  5
1  0 -6
2  3  7
3  0 -8
4  5  9


In [26]:
#26
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# Accessing the 3rd element (index 2)
third_element = arr[2]
print(third_element)


30


In [27]:
#27
import numpy as np

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Retrieving the element at index (1, 2)
element = arr_2d[1, 2]
print(element)


6


In [28]:
#28
import numpy as np

arr = np.array([3, 8, 2, 10, 5, 7])

# Extracting elements greater than 5
greater_than_five = arr[arr > 5]
print(greater_than_five)


[ 8 10  7]


In [29]:
#29
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Extracting elements from index 2 to 5 (inclusive)
sliced_arr = arr[2:6]  # Slicing up to index 6 to include the element at index 5
print(sliced_arr)


[3 4 5 6]


In [30]:
#30
import numpy as np

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Slicing to extract the sub-array [[2, 3], [5, 6]]
sub_array = arr_2d[0:2, 1:3]
print(sub_array)


[[2 3]
 [5 6]]


In [31]:
#31
import numpy as np

def extract_elements_2d(arr, row_indices, col_indices):
    return arr[row_indices, col_indices]

# Example usage
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
row_indices = np.array([0, 1, 2])
col_indices = np.array([2, 1, 0])

extracted_elements = extract_elements_2d(arr, row_indices, col_indices)
print(extracted_elements)


[3 5 7]


In [32]:
#32
import numpy as np

def filter_greater_than_threshold(arr, threshold):
    return arr[arr > threshold]

# Example usage
arr = np.array([10, 20, 5, 15, 25])
threshold = 15

filtered_arr = filter_greater_than_threshold(arr, threshold)
print(filtered_arr)


[20 25]


In [33]:
#33
import numpy as np

def extract_elements_3d(arr, x_indices, y_indices, z_indices):
    return arr[x_indices, y_indices, z_indices]

# Example usage
arr = np.arange(27).reshape(3, 3, 3)
x_indices = np.array([0, 1, 2])
y_indices = np.array([1, 0, 2])
z_indices = np.array([2, 1, 0])

extracted_elements = extract_elements_3d(arr, x_indices, y_indices, z_indices)
print(extracted_elements)


[ 5 10 24]


In [34]:
#34
import numpy as np

def filter_by_two_conditions(arr, condition1, condition2):
    return arr[np.logical_and(condition1, condition2)]

# Example usage
arr = np.array([10, 20, 5, 15, 25])
condition1 = arr > 10
condition2 = arr < 25

filtered_arr = filter_by_two_conditions(arr, condition1, condition2)
print(filtered_arr)


[20 15]


In [35]:
#35
import numpy as np

def extract_elements_by_indices(arr, row_indices, col_indices):
    return arr[row_indices, col_indices]

# Example usage
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
row_indices = np.array([0, 2])
col_indices = np.array([1, 2])

extracted_elements = extract_elements_by_indices(arr, row_indices, col_indices)
print(extracted_elements)


[2 9]


In [36]:
#36
import numpy as np

def add_scalar(arr, scalar):
    return arr + scalar

# Example usage
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

result = add_scalar(arr, 5)
print(result)


[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [37]:
#37
import numpy as np

def multiply_rows_by_elements(arr1, arr2):
    return arr1 * arr2

# Example usage
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[4, 5, 6, 7],
                 [8, 9, 10, 11],
                 [12, 13, 14, 15]])

result = multiply_rows_by_elements(arr1.T, arr2)
print(result)


[[ 4  5  6  7]
 [16 18 20 22]
 [36 39 42 45]]


In [38]:
#38
import numpy as np

def add_arr1_to_arr2(arr1, arr2):
    return arr1 + arr2

# Example usage
arr1 = np.array([[1, 2, 3, 4]])
arr2 = np.array([[5, 6, 7, 8],
                 [9, 10, 11, 12],
                 [13, 14, 15, 16]])

result = add_arr1_to_arr2(arr1, arr2)
print(result)


[[ 6  8 10 12]
 [10 12 14 16]
 [14 16 18 20]]


In [39]:
#39
import numpy as np

def add_broadcasted(arr1, arr2):
    return arr1 + arr2

# Example usage
arr1 = np.array([[1], [2], [3]])
arr2 = np.array([[4, 5, 6]])

result = add_broadcasted(arr1, arr2)
print(result)


[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [40]:
#40
import numpy as np

def multiply_with_broadcasting(arr1, arr2):
    try:
        result = arr1 * arr2
    except ValueError as e:
        print("Shape incompatibility: ", e)
        return None
    return result

# Example usage
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr2 = np.array([[7, 8],
                 [9, 10]])

result = multiply_with_broadcasting(arr1, arr2)
print(result)


Shape incompatibility:  operands could not be broadcast together with shapes (2,3) (2,2) 
None


In [41]:
#41
import numpy as np

def column_wise_mean(arr):
    return np.mean(arr, axis=0)

# Example usage
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

column_means = column_wise_mean(arr)
print(column_means)


[2.5 3.5 4.5]


In [42]:
#42
import numpy as np

def row_wise_max(arr):
    return np.max(arr, axis=1)

# Example usage
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

row_max_values = row_wise_max(arr)
print(row_max_values)


[3 6]


In [43]:
#43
import numpy as np

def max_value_indices_per_column(arr):
    return np.argmax(arr, axis=0)

# Example usage
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

max_indices = max_value_indices_per_column(arr)
print(max_indices)


[1 1 1]


In [44]:
#44
import numpy as np

def moving_sum(arr, window_size):
    return np.apply_along_axis(lambda x: np.convolve(x, np.ones(window_size), 'valid'), axis=1, arr=arr)

# Example usage
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
window_size = 2

moving_sums = moving_sum(arr, window_size)
print(moving_sums)


[[ 3.  5.]
 [ 9. 11.]]


In [45]:
#45
import numpy as np

def all_even_in_columns(arr):
    return np.all(arr % 2 == 0, axis=0)

# Example usage
arr = np.array([[2, 4, 6],
                [3, 5, 7]])

all_even = all_even_in_columns(arr)
print(all_even)


[False False False]


In [46]:
#46
import numpy as np

def reshape_array(arr, m, n):
    return arr.reshape(m, n)

# Example usage
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_matrix = reshape_array(arr, 2, 3)
print(reshaped_matrix)


[[1 2 3]
 [4 5 6]]


In [47]:
#47
import numpy as np

def flatten_matrix(matrix):
    return matrix.flatten()

# Example usage
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
flattened_array = flatten_matrix(input_matrix)
print(flattened_array)


[1 2 3 4 5 6]


In [48]:
#48
import numpy as np

def concatenate_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)

# Example usage
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
concatenated_array = concatenate_arrays(array1, array2, axis=0)
print(concatenated_array)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [49]:
#49
import numpy as np

def split_array(arr, num_splits, axis=0):
    return np.array_split(arr, num_splits, axis=axis)

# Example usage
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sub_arrays = split_array(original_array, 3, axis=1)
print(sub_arrays)


[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


In [50]:
#50
import numpy as np

def insert_and_delete(arr, insert_indices, insert_values, delete_indices):
    arr = np.insert(arr, insert_indices, insert_values)
    arr = np.delete(arr, delete_indices)
    return arr

# Example usage
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

modified_array = insert_and_delete(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print(modified_array)


[ 1 10  4 11  5]


In [51]:
#51
import numpy as np

def element_wise_addition(arr1, arr2):
    return arr1 + arr2

# Example usage
arr1 = np.random.randint(1, 10, size=(5,))
arr2 = np.array([1, 2, 3, 4, 5])
result = element_wise_addition(arr1, arr2)
print(result)


[ 8  7 12 11 11]


In [52]:
#52
import numpy as np

def element_wise_subtraction(arr1, arr2):
    return arr1 - arr2

# Example usage
arr1 = np.arange(10, 0, -1)
arr2 = np.arange(1, 11)
result = element_wise_subtraction(arr1, arr2)
print(result)


[ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [53]:
#53
import numpy as np

def element_wise_multiplication(arr1, arr2):
    return arr1 * arr2

# Example usage
arr1 = np.random.randint(1, 10, size=(5,))
arr2 = np.array([1, 2, 3, 4, 5])
result = element_wise_multiplication(arr1, arr2)
print(result)


[ 9 16 15 12  5]


In [54]:
#54
import numpy as np

def element_wise_division(arr1, arr2):
    return arr1 / arr2

# Example usage
arr1 = np.arange(2, 11, 2)
arr2 = np.arange(1, 6)
result = element_wise_division(arr1, arr2)
print(result)


[2. 2. 2. 2. 2.]


In [55]:
#55
import numpy as np

def element_wise_exponentiation(arr1, arr2):
    return np.power(arr1, arr2)

# Example usage
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])
result = element_wise_exponentiation(arr1, arr2)
print(result)


[ 1 16 27 16  5]


In [56]:
#56
import numpy as np

def count_substring_occurrences(arr, substring):
    return np.char.count(arr, substring)

# Example usage
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'
count = count_substring_occurrences(arr, substring)
print(count)


[1 0 1 0 1]


In [57]:
#57
import numpy as np

def extract_uppercase_characters(arr):
    return np.char.join('', np.char.upper(arr))

# Example usage
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
uppercase_chars = extract_uppercase_characters(arr)
print(uppercase_chars)


['HELLO' 'WORLD' 'OPENAI' 'GPT']


In [58]:
#58
import numpy as np

def replace_substring(arr, old_substring, new_substring):
    return np.char.replace(arr, old_substring, new_substring)

# Example usage
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
result = replace_substring(arr, 'apple', 'orange')
print(result)  # Output: ['orange' 'banana' 'grape' 'orange']


['orange' 'banana' 'grape' 'pineorange']


In [59]:
#59
import numpy as np

def concatenate_strings(arr1, arr2):
    return np.char.add(arr1, arr2)

# Example usage
arr1 = np.array(['Hello', 'World'])
arr2 = np.array([' Open', ' AI'])
result = concatenate_strings(arr1, arr2)
print(result)  # Output: ['Hello Open' 'World AI']


['Hello Open' 'World AI']


In [60]:
#60
import numpy as np

def longest_string_length(arr):
    return np.max(np.char.str_len(arr))

# Example usage
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
result = longest_string_length(arr)
print(result)  # Output: 9


9


In [61]:
#61
import numpy as np

# Create a dataset of 100 random integers between 1 and 1000
data = np.random.randint(1, 1001, size=100)

mean = np.mean(data)
median = np.median(data)
variance = np.var(data)
std_dev = np.std(data)

print(f'Mean: {mean}')
print(f'Median: {median}')
print(f'Variance: {variance}')
print(f'Standard Deviation: {std_dev}')


Mean: 553.33
Median: 580.5
Variance: 86956.5611
Standard Deviation: 294.8839790493882


In [62]:
#62
import numpy as np

# Generate an array of 50 random numbers between 1 and 100
data = np.random.randint(1, 101, size=50)

percentile_25 = np.percentile(data, 25)
percentile_75 = np.percentile(data, 75)

print(f'25th Percentile: {percentile_25}')
print(f'75th Percentile: {percentile_75}')


25th Percentile: 33.25
75th Percentile: 78.5


In [63]:
#63
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

correlation = np.corrcoef(arr1, arr2)[0, 1]
print(f'Correlation Coefficient: {correlation}')


Correlation Coefficient: 1.0


In [64]:
#64
import numpy as np

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

result = np.dot(matrix1, matrix2)
print(result)


[[19 22]
 [43 50]]


In [65]:
#65
import numpy as np

data = np.random.randint(10, 1001, size=50)

percentile_10 = np.percentile(data, 10)
percentile_50 = np.percentile(data, 50)
percentile_90 = np.percentile(data, 90)

quartile_1 = np.percentile(data, 25)
quartile_3 = np.percentile(data, 75)

print(f'10th Percentile: {percentile_10}')
print(f'50th Percentile (Median): {percentile_50}')
print(f'90th Percentile: {percentile_90}')
print(f'1st Quartile: {quartile_1}')
print(f'3rd Quartile: {quartile_3}')


10th Percentile: 170.7
50th Percentile (Median): 584.0
90th Percentile: 913.2
1st Quartile: 337.25
3rd Quartile: 778.0


In [66]:
#66
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

index = np.where(arr == 30)[0]
print(f'Index of 30: {index}')


Index of 30: [2]


In [67]:
#67
import numpy as np

arr = np.random.randint(1, 100, size=20)
sorted_arr = np.sort(arr)
print(f'Sorted Array: {sorted_arr}')


Sorted Array: [ 3  5  7 12 19 29 33 36 48 50 56 58 66 68 68 70 72 73 79 88]


In [ ]:
#